name: Build Overlay

on:
  push:
    branches:
      - master
  workflow_dispatch: # Enables the manual 'Run Workflow' button in GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          submodules: 'true'

      - name: Build
        run: make

      # - name: Upload packages to release
      #   uses: ncipollo/release-action@v1.8.10
      #   with:
      #     allowUpdates: true
      #     artifactErrorsFailBuild: true
      #     artifacts: ./bin/*.+(db|files|gz|zst)
      #     tag: repository
      #     commit: master
      #     token: ${{ secrets.GITHUB_TOKEN }}
